### ISSUE TITLE
text in calendar is not readable

### ISSUE THREAD

**Issue by davekch** [vinceliuice/Graphite-gtk-theme#122]
the description text of events in the gnome calendar is very hard to read:
![Screenshot from 2023-11-22 23-01-08](https://github.com/vinceliuice/Graphite-gtk-theme/assets/35708136/e74c0407-dceb-47bf-80b2-40f0486effa4)

I am using the black variant of the theme (`./install.sh -c dark --libadwaita --tweaks rimless normal black`)

**Comment by davekch** [comment]
I noticed it can be fixed by adding
```css
event label {
  color: rgba(255, 255, 255, 0.7);
}
```
to `gtk.css`
