### ISSUE TITLE
dashtodock has extra bottom padding

### ISSUE THREAD

**Issue by JaxonWright** [vinceliuice/Graphite-gtk-theme#137]
![image](https://github.com/vinceliuice/Graphite-gtk-theme/assets/14099593/a1413524-f3fd-4d61-94d8-00fd27e2054e)

I have tried to find where in the `gnome-shell.css` that this problem is caused by, but I cannot. Even adjusting the margin and padding manually does nothing.

This only applies to a bottom-pinned dock.

**Comment by vinceliuice** [comment]
You should change the `dash to dock` setting !

**Comment by JaxonWright** [comment]
@vinceliuice can you give me more insight on where/what that is?

**Comment by JaxonWright** [comment]
I found the issue finally. In the CSS, you need to make the following change:
```css
.dash-item-container .app-well-app, .dash-item-container .show-apps {
-   padding: 10px 0 26px !important;
+  padding: 10px 0 0px !important;
  border-radius: 12px;
}
```
