### ISSUE TITLE
Windows border color adjustments

### ISSUE THREAD

**Issue by dxps** [vinceliuice/Graphite-gtk-theme#17]
Dear Vince,

Thanks a lot for this wonderful theme you shared with the GNOME community! :heart_eyes:  :pray: 
I'm on Pop!_OS and just switched to it (the dark version).

Just as a hint, could you please share some hints for how shall I adjust a little bit the border color (less white) of the windows :question: 

I tried updating all `border: 1px solid rgba(255, 255, 255, 0.12);` entries in `gtk-dark.css` file, such as this one:
```css
frame,
.frame {
  border: 1px solid rgba(100, 100, 100, 0.12);
}
```
but without a change.

![image](https://user-images.githubusercontent.com/14140226/145003428-72b00243-fe13-4a7e-9c32-102807588611.png)

Thank you!

**Comment by vinceliuice** [comment]
It's not frame, you need change this https://github.com/vinceliuice/Graphite-gtk-theme/blob/dad4504505c7f861df5dcf9c77ee7218a7a19566/src/sass/gtk/_common-3.0.scss#L3614

**Comment by dxps** [comment]
Thanks for the feedback!
Tried with both a variable (defined in `src/sass/_colors.scss` file) or "hardcoded" like this:
```css
/**********************
 * Window Decorations *
 **********************/
decoration {
  transition: $transition-shadow;

  @if $rimless == 'true' {
    border-radius: $window-radius;
    box-shadow: $shadow-z16, 0 0 36px transparent;
  } @else {
    border-radius: $window-radius + 2px;
    box-shadow: $shadow-z4, 0 0 16px transparent;
    border: 2px solid #5C5C5C;  // <---- LIKE THIS
    background-clip: border-box;
  }
  ...
```
the problems are:
1. Installing it using `./install.sh` it seems that this `#5C5C5C` is not reflected in the result
   (in any of theme flavors installed in `~/.themes/` directory, `grep -R "5C5C5C" *` shows no finding).
2. Otherwise, trying to install without the border using `./install --tweaks rimless` fails
   and no Graphite flavor gets "installed" into `~/.themes` directory)
   ```shell
   $ ./install.sh --tweaks rimless

   ** (process:1011735): WARNING **: 14:40:09.222: Failed to set RT scheduler: Operation not permitted
   Install Rimless version! ...
   Installing '/home/dxps/.themes/Graphite'...
   cp: target 'Graphite/Graphite-gtk-theme/src/sass/_tweaks-temp.scss' is not a directory
   $
   ```

I don't wanna offload all of these to you, I'll try to solve on my own and get back with a feedback, but I wanted to raise the issues and what I tried in this regard.

Thanks.
