### ISSUE TITLE
Headerbar, Titlebar custom background: not working for Nautilus and GTK2 apps

### ISSUE THREAD

**Issue by Trikenstein** [vinceliuice/Graphite-gtk-theme#3]
Hi,

This might be outside of your theme design but I would really appreciate if you can help to fix. I prefer to have a colored titlebar because this helps me to see better the various windows. 

I added at the bottom of ~/.themes/Graphite-blue-dark-compact-nord/gtk-3.0/gtk.css

```css
.titlebar, headerbar {
  background-color: #0063b3;
}
.titlebar:backdrop, headerbar:backdrop {
  background-color: #003a6a;
}
```

This almost works, except that some applications ignore the custom background (BG) colors. See screenshot. FYI I am able to apply this trick on themes such as:

- [Juno](https://www.gnome-look.org/p/1280977/)
- [Nordic](https://www.gnome-look.org/p/1267246)
- [Marwaita](https://www.gnome-look.org/p/1239855)

![Graphite_customBGcolor_headerbar-titlebar](https://user-images.githubusercontent.com/72353094/133941369-37f3eba1-14b5-488f-812c-b132169dc941.png)
