### ISSUE TITLE
Top bar font size is too small on 4K resolution

### ISSUE THREAD

**Issue by enginhu** [vinceliuice/Graphite-gtk-theme#92]
Hi,
How can u increase the font size of top bar?
I couldn't fin the css selector in gnome-shell.css.

**Comment by JerryPenguin** [comment]
i am missind the HD option too

**Comment by leoniscsem** [comment]
Go to `{Graphite theme}/gnome-shell/gnome-shell.css` and find the following entries:

```css
#panel {
  font-weight: bold;
  ...
  font-size: 11pt;  # set font size according to your taste
  background-color: #292e38;
  height: 32px;
}
```

```css
.popup-menu {
  ...
  font-weight: normal;
  font-size: 12pt; # set font size according to your taste
}
```
